-- ============================================================
-- EXECUTAR COMO ocorrencias_app
-- Conectar em: sqlplus ocorrencias_app/senha@192.168.0.98:1521/WINT
-- ============================================================


-- ============================================================
-- TABELA: usuarios
-- ============================================================

CREATE TABLE usuarios (
    id          INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR2(200)   NOT NULL,
    email       VARCHAR2(200)   NOT NULL,
    senha_hash  VARCHAR2(255)   NOT NULL,
    papel       VARCHAR2(20)    NOT NULL,   -- OPERADOR | GERENTE
    ativo       NUMBER(1)       DEFAULT 1 NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_papel CHECK (papel IN ('OPERADOR', 'GERENTE')),
    CONSTRAINT ck_usuarios_ativo CHECK (ativo IN (0, 1))
);

-- Trigger para atualizar updated_at automaticamente
CREATE OR REPLACE TRIGGER trg_usuarios_updated_at
BEFORE UPDATE ON usuarios
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/


-- ============================================================
-- TABELA: ocorrencias
-- ============================================================

CREATE TABLE ocorrencias (
    id                   INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_carregamento  VARCHAR2(50)    NOT NULL,
    tipo_carregamento    VARCHAR2(20)    DEFAULT 'INTERNO' NOT NULL,

    -- Nota fiscal selecionada pelo usuário
    numero_nota_fiscal   VARCHAR2(50)    NOT NULL,

    -- Snapshot dos dados do carregamento no momento da criação
    data_saida_carga     DATE,
    cliente              VARCHAR2(200),
    motorista            VARCHAR2(200),
    vendedor             VARCHAR2(200),

    -- Dados da ocorrência
    situacao             VARCHAR2(50)    NOT NULL,
    motivo               VARCHAR2(1000),
    observacoes          VARCHAR2(2000),

    -- Status do fluxo
    status               VARCHAR2(30)    DEFAULT 'NOVO' NOT NULL,

    -- Relacionamentos
    criado_por_id        INTEGER         NOT NULL,
    aprovado_por_id      INTEGER,
    aprovado_em          TIMESTAMP,

    created_at           TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ocor_criado_por  FOREIGN KEY (criado_por_id)   REFERENCES usuarios(id),
    CONSTRAINT fk_ocor_aprovado_por FOREIGN KEY (aprovado_por_id) REFERENCES usuarios(id),

    CONSTRAINT ck_ocor_tipo   CHECK (tipo_carregamento IN ('INTERNO', 'TRANSPORTADORA')),
    CONSTRAINT ck_ocor_situacao CHECK (situacao IN (
        'DEVOLUCAO_TOTAL', 'DEVOLUCAO_PARCIAL', 'FALTAS',
        'INVERSAO_MERCADORIAS', 'SOBRAS', 'AVARIAS', 'COLETAS'
    )),
    CONSTRAINT ck_ocor_status CHECK (status IN (
        'NOVO', 'EM_RESOLUCAO', 'PENDENTE', 'CONCLUIDO', 'FINALIZADO'
    ))
);

-- Índices para filtros comuns
CREATE INDEX idx_ocor_criado_por   ON ocorrencias (criado_por_id);
CREATE INDEX idx_ocor_status       ON ocorrencias (status);
CREATE INDEX idx_ocor_numcar       ON ocorrencias (numero_carregamento);
CREATE INDEX idx_ocor_created_at   ON ocorrencias (created_at);

-- Trigger para atualizar updated_at automaticamente
CREATE OR REPLACE TRIGGER trg_ocorrencias_updated_at
BEFORE UPDATE ON ocorrencias
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/


COMMIT;
