-- ============================================================
-- EXECUTAR COMO gestao_sac
-- ============================================================


-- ============================================================
-- TABELA: ocorrencias
-- ============================================================

CREATE TABLE ocorrencias (
    id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,

    -- Nota fiscal
    numero_nota_fiscal      VARCHAR2(50)    NOT NULL,

    -- Snapshot do CEDEP no momento da criação
    id_carregamento         INTEGER,
    data_faturamento        DATE,
    data_saida_carregamento DATE,
    cliente                 VARCHAR2(200),
    motorista               VARCHAR2(200),
    vendedor                VARCHAR2(200),
    valor_total             NUMBER(15, 2),

    -- Dados da ocorrência
    situacao                VARCHAR2(50)    NOT NULL,
    motivo                  VARCHAR2(1000),
    observacoes             VARCHAR2(2000),
    encaminhamento          VARCHAR2(2000),

    -- Status
    status                  VARCHAR2(20)    DEFAULT 'NOVO' NOT NULL,

    -- Relacionamentos
    criado_por_id           INTEGER         NOT NULL,
    aprovado_por_id         INTEGER,
    aprovado_em             TIMESTAMP,

    created_at              TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ocor_criado_por   FOREIGN KEY (criado_por_id)   REFERENCES usuarios(id),
    CONSTRAINT fk_ocor_aprovado_por FOREIGN KEY (aprovado_por_id) REFERENCES usuarios(id),
    CONSTRAINT ck_ocor_situacao CHECK (situacao IN (
        'DEVOLUCAO_TOTAL', 'DEVOLUCAO_PARCIAL', 'INVERSAO_MERCADORIA',
        'SOBRA', 'AVARIA', 'COLETA'
    )),
    CONSTRAINT ck_ocor_status CHECK (status IN ('NOVO', 'ENCAMINHADO', 'FINALIZADO'))
);

CREATE INDEX idx_ocor_nota      ON ocorrencias (numero_nota_fiscal);
CREATE INDEX idx_ocor_criado    ON ocorrencias (criado_por_id);
CREATE INDEX idx_ocor_status    ON ocorrencias (status);
CREATE INDEX idx_ocor_created   ON ocorrencias (created_at);

CREATE OR REPLACE TRIGGER trg_ocorrencias_updated_at
BEFORE UPDATE ON ocorrencias
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/


-- ============================================================
-- TABELA: anexos
-- ============================================================

CREATE TABLE anexos (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ocorrencia_id   INTEGER         NOT NULL,
    nome_arquivo    VARCHAR2(255)   NOT NULL,
    caminho_arquivo VARCHAR2(500)   NOT NULL,
    mime_type       VARCHAR2(100),
    tamanho         INTEGER,
    criado_por_id   INTEGER         NOT NULL,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_anexo_ocorrencia  FOREIGN KEY (ocorrencia_id) REFERENCES ocorrencias(id),
    CONSTRAINT fk_anexo_criado_por  FOREIGN KEY (criado_por_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_anexo_ocorrencia ON anexos (ocorrencia_id);


COMMIT;
