-- ============================================================
-- EXECUTAR COMO gestao_sac
-- Recria tabela anexos com IDENTITY correto no id
-- ============================================================

DROP TABLE anexos;

CREATE TABLE anexos (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ocorrencia_id   INTEGER         NOT NULL,
    nome_arquivo    VARCHAR2(255)   NOT NULL,
    caminho_arquivo VARCHAR2(500)   NOT NULL,
    mime_type       VARCHAR2(100),
    tamanho         INTEGER,
    criado_por_id   INTEGER         NOT NULL,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_anexo_ocorrencia  FOREIGN KEY (ocorrencia_id) REFERENCES ocorrencias(id),
    CONSTRAINT fk_anexo_criado_por  FOREIGN KEY (criado_por_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_anexo_ocorrencia ON anexos (ocorrencia_id);

COMMIT;
