-- ============================================================
-- MIGRATION 07: refatoração do fluxo de ocorrências
-- EXECUTAR COMO gestao_sac
-- ============================================================

-- 1. Novo conjunto de status
ALTER TABLE ocorrencias DROP CONSTRAINT ck_ocor_status;
ALTER TABLE ocorrencias ADD CONSTRAINT ck_ocor_status CHECK (status IN (
    'EM_TRATAMENTO', 'PENDENTE', 'ENCAMINHADO', 'CONCLUIDO', 'FINALIZADO'
));

-- Migrar status antigos
UPDATE ocorrencias SET status = 'EM_TRATAMENTO' WHERE status = 'NOVO';
-- ENCAMINHADO e FINALIZADO permanecem


-- 2. Novas colunas em ocorrencias
ALTER TABLE ocorrencias ADD transportadora           VARCHAR2(200);
ALTER TABLE ocorrencias ADD atribuido_a_id           INTEGER;
ALTER TABLE ocorrencias ADD tipo_ocorrencia          VARCHAR2(50);
ALTER TABLE ocorrencias ADD causa_raiz               VARCHAR2(50);
ALTER TABLE ocorrencias ADD responsavel_tipo         VARCHAR2(50);
ALTER TABLE ocorrencias ADD responsavel_descricao    VARCHAR2(200);
ALTER TABLE ocorrencias ADD setor_destino            VARCHAR2(50);
ALTER TABLE ocorrencias ADD impacto                  VARCHAR2(50);
ALTER TABLE ocorrencias ADD descricao                VARCHAR2(2000);
ALTER TABLE ocorrencias ADD motivo_pendencia         VARCHAR2(1000);
ALTER TABLE ocorrencias ADD resolucao_encaminhamento VARCHAR2(2000);
ALTER TABLE ocorrencias ADD resolucao_final          VARCHAR2(2000);
ALTER TABLE ocorrencias ADD detalhes_especificos     CLOB;

ALTER TABLE ocorrencias ADD CONSTRAINT fk_ocor_atribuido
    FOREIGN KEY (atribuido_a_id) REFERENCES usuarios(id);
ALTER TABLE ocorrencias ADD CONSTRAINT ck_ocor_detalhes_json
    CHECK (detalhes_especificos IS JSON);


-- 3. Backfill: atribuir o criador a quem não tem responsável
UPDATE ocorrencias SET atribuido_a_id = criado_por_id WHERE atribuido_a_id IS NULL;
ALTER TABLE ocorrencias MODIFY atribuido_a_id INTEGER NOT NULL;


-- 4. Migrar situacao antiga -> tipo_ocorrencia
UPDATE ocorrencias SET tipo_ocorrencia = CASE situacao
    WHEN 'DEVOLUCAO_TOTAL'     THEN 'DEVOLUCAO_SOLICITADA'
    WHEN 'DEVOLUCAO_PARCIAL'   THEN 'DEVOLUCAO_SOLICITADA'
    WHEN 'INVERSAO_MERCADORIA' THEN 'INVERSAO_MERCADORIA'
    WHEN 'SOBRA'               THEN 'SOBRA_MERCADORIA'
    WHEN 'AVARIA'              THEN 'AVARIA'
    WHEN 'COLETA'              THEN 'DEVOLUCAO_SOLICITADA'
    ELSE 'OUTRO'
END;

ALTER TABLE ocorrencias MODIFY tipo_ocorrencia VARCHAR2(50) NOT NULL;

ALTER TABLE ocorrencias ADD CONSTRAINT ck_ocor_tipo CHECK (tipo_ocorrencia IN (
    'AVARIA', 'INVERSAO_MERCADORIA', 'FALTA_MERCADORIA', 'SOBRA_MERCADORIA',
    'DEVOLUCAO_SOLICITADA', 'PEDIDO_TROCA', 'EXTRAVIO', 'ATRASO_ENTREGA',
    'ERRO_CADASTRO', 'PEDIDO_DUPLICADO', 'PEDIDO_DESACORDO',
    'SOLICITACAO_FINANCEIRA', 'OUTRO'
));

-- 5. Marcar coluna situacao como UNUSED (não dropar ainda — manter para rollback)
ALTER TABLE ocorrencias SET UNUSED COLUMN situacao;


-- 6. Tabela de itens afetados
CREATE TABLE ocorrencia_itens (
    id                INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ocorrencia_id     INTEGER         NOT NULL,
    codprod           VARCHAR2(20),
    descricao_produto VARCHAR2(200),
    qtd_afetada       NUMBER(15, 3),
    valor_unitario    NUMBER(15, 2),
    valor_total       NUMBER(15, 2),
    item_role         VARCHAR2(30)    DEFAULT 'AFETADO' NOT NULL,
    created_at        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_oitem_ocor FOREIGN KEY (ocorrencia_id)
        REFERENCES ocorrencias(id) ON DELETE CASCADE,
    CONSTRAINT ck_oitem_role CHECK (item_role IN
        ('AFETADO', 'ENVIADO_INCORRETAMENTE', 'ITEM_CORRETO'))
);
CREATE INDEX idx_oitem_ocor ON ocorrencia_itens (ocorrencia_id);


-- 7. Tabela de eventos (timeline / audit log)
CREATE TABLE ocorrencia_eventos (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ocorrencia_id   INTEGER         NOT NULL,
    tipo_evento     VARCHAR2(30)    NOT NULL,
    status_anterior VARCHAR2(30),
    status_novo     VARCHAR2(30),
    comentario      VARCHAR2(2000),
    usuario_id      INTEGER         NOT NULL,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_oevt_ocor FOREIGN KEY (ocorrencia_id)
        REFERENCES ocorrencias(id) ON DELETE CASCADE,
    CONSTRAINT fk_oevt_user FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT ck_oevt_tipo CHECK (tipo_evento IN (
        'CRIADA', 'COMENTARIO', 'MUDANCA_STATUS', 'ANEXO_ADICIONADO',
        'ITEM_ADICIONADO', 'APROVADA', 'REPROVADA', 'ATRIBUICAO_ALTERADA'
    ))
);
CREATE INDEX idx_oevt_ocor ON ocorrencia_eventos (ocorrencia_id, created_at);


-- 8. Índices auxiliares para filtros da lista
CREATE INDEX idx_ocor_tipo       ON ocorrencias (tipo_ocorrencia);
CREATE INDEX idx_ocor_atribuido  ON ocorrencias (atribuido_a_id);
CREATE INDEX idx_ocor_resp_tipo  ON ocorrencias (responsavel_tipo);

COMMIT;
